import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { chmodSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { validateWorkbenchLiveRouteEvidenceArtifact } from "../src/workflow/live-route-acceptance.js";
import { probeWorkbenchLiveRoute } from "../tools/probe-workbench-live-route.mjs";

const SECRET_COOKIE = "hz_auth_session=secret-cookie-value";
const SECRET_HEADER = "Bearer secret-header-value";
const ROUTE_URL = "http://127.0.0.1:4180/projects/ai-control-platform/";
const SHARED_EDGE_ROUTE_URL = "https://hernando-zhao.cn/projects/ai-control-platform/";
const UNREACHABLE_ROUTE_URL = "http://127.0.0.1:0/projects/ai-control-platform/";

function projectStatus(routeUrl = ROUTE_URL) {
  return {
    project: "ai-control-platform",
    blockers: [
      {
        id: "public-project-route-auth-gate",
        category: "canonical_route_unverified",
        severity: "p1",
        evidence: `Authenticate and verify https://hernando-zhao.cn/projects/ai-control-platform/; test stub route is ${routeUrl}`
      }
    ],
    next_step: "Probe authenticated public workbench route.",
    latest_update: "Live-route evidence must be generated by probe."
  };
}

function writeProjectStatus(dir, routeUrl = ROUTE_URL) {
  const statusPath = join(dir, "PROJECT_STATUS.json");
  writeFileSync(statusPath, `${JSON.stringify(projectStatus(routeUrl), null, 2)}\n`);
  return statusPath;
}

function stubTransport(url, headers) {
  const authorized = (headers.Cookie === SECRET_COOKIE && headers.Authorization === SECRET_HEADER) ||
    headers["X-HZ-Dev-Auth-Bypass-Token"] === "secret-header-value";
  const redirect = {
    url,
    finalUrl: "http://127.0.0.1:4180/?next=%2Fprojects%2Fai-control-platform%2F",
    status: 302,
    headers: {
      location: "/?next=%2Fprojects%2Fai-control-platform%2F",
      "set-cookie": ["hz_auth_session=; Path=/; Max-Age=0"]
    },
    body: "login required",
    redirects: [
      {
        from_url: url,
        to_url: "http://127.0.0.1:4180/?next=%2Fprojects%2Fai-control-platform%2F",
        http_status: 302,
        auth_redirect_detected: true
      }
    ],
    authRedirectDetected: true
  };
  if (!authorized) return Promise.resolve(redirect);
  const pathname = new URL(url).pathname;
  if (pathname === "/projects/ai-control-platform/" || pathname === "/projects/ai-control-platform/apps/workbench/desktop.html") {
    return Promise.resolve({
      url,
      finalUrl: url,
      status: 200,
      headers: { "content-type": "text/html; charset=utf-8" },
      body: "<!doctype html><title>AI Control Platform Workbench</title><body data-view=\"desktop\"><main data-bind=\"headline\">Workbench</main></body>",
      redirects: [],
      authRedirectDetected: false
    });
  }
  if (pathname === "/projects/ai-control-platform/api/workbench/projection") {
    return Promise.resolve({
      url,
      finalUrl: url,
      status: 200,
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ projection_id: "stub", status: "pass" }),
      redirects: [],
      authRedirectDetected: false
    });
  }
  return Promise.resolve({
    url,
    finalUrl: url,
    status: 404,
    headers: {},
    body: "not found",
    redirects: [],
    authRedirectDetected: false
  });
}

async function runCli(args) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, ["tools/probe-workbench-live-route.mjs", ...args], {
      cwd: process.cwd(),
      stdio: ["ignore", "pipe", "pipe"]
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (status) => {
      resolve({ status, stdout, stderr });
    });
  });
}

test("probe writes failed evidence for unauthenticated auth redirect", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ai-control-platform-live-probe-"));
  const statusPath = writeProjectStatus(dir);
  const artifact = await probeWorkbenchLiveRoute({
    projectStatusPath: statusPath,
    url: ROUTE_URL,
    allowInsecureLocalTest: true,
    headers: {},
    headerNames: [],
    requestText: stubTransport
  });

  assert.equal(artifact.version, "workbench-live-route-evidence.v1");
  assert.equal(artifact.status, "fail");
  assert.equal(artifact.auth_redirect_detected, true);
  assert.equal(artifact.local_loopback, true);
  assert.ok(artifact.issues.some((issue) => issue.code === "route_auth_redirect_detected"));
});

test("probe writes authenticated local stub pass evidence accepted only in local test mode", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ai-control-platform-live-probe-"));
  const statusPath = writeProjectStatus(dir);
  const artifact = await probeWorkbenchLiveRoute({
    projectStatusPath: statusPath,
    url: ROUTE_URL,
    allowInsecureLocalTest: true,
    headers: {
      Cookie: SECRET_COOKIE,
      Authorization: SECRET_HEADER
    },
    headerNames: ["Cookie", "Authorization"],
    requestText: stubTransport
  });
  const testValidation = validateWorkbenchLiveRouteEvidenceArtifact(artifact, {
    projectId: "ai-control-platform",
    expectedRouteUrls: ["https://hernando-zhao.cn/projects/ai-control-platform/"],
    allowInsecureLocalTest: true
  });
  const realValidation = validateWorkbenchLiveRouteEvidenceArtifact(artifact, {
    projectId: "ai-control-platform",
    expectedRouteUrls: ["https://hernando-zhao.cn/projects/ai-control-platform/"]
  });

  assert.equal(artifact.status, "pass");
  assert.equal(artifact.local_loopback, true);
  assert.equal(artifact.public_route_verified, true);
  assert.equal(artifact.mounted_workbench_route_verified, true);
  assert.equal(artifact.workbench_rendered, true);
  assert.equal(artifact.mounted_api_verified, true);
  assert.equal(testValidation.status, "pass");
  assert.equal(realValidation.status, "fail");
  assert.ok(realValidation.issues.some((issue) => issue.code === "local_live_route_evidence_not_allowed"));
});

test("probe auto-injects shared edge agent auth from env without printing the value", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ai-control-platform-live-probe-"));
  const statusPath = writeProjectStatus(dir, SHARED_EDGE_ROUTE_URL);
  const artifact = await probeWorkbenchLiveRoute({
    projectStatusPath: statusPath,
    url: SHARED_EDGE_ROUTE_URL,
    allowInsecureLocalTest: true,
    headers: {},
    headerNames: [],
    env: {
      HZ_DEV_AUTH_BYPASS_TOKEN: "secret-header-value"
    },
    requestText: stubTransport
  });

  assert.equal(artifact.status, "pass");
  assert.deepEqual(artifact.request_header_names, ["X-HZ-Dev-Auth-Bypass-Token"]);
  assert.doesNotMatch(JSON.stringify(artifact), /secret-header-value/);
});

test("probe auto-injects shared edge agent auth from helper when env token is absent", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ai-control-platform-live-probe-"));
  const statusPath = writeProjectStatus(dir, SHARED_EDGE_ROUTE_URL);
  const helperPath = join(dir, "edge-agent-auth-token.sh");
  writeFileSync(helperPath, "#!/usr/bin/env bash\nprintf '%s\\n' secret-header-value\n");
  chmodSync(helperPath, 0o700);

  const artifact = await probeWorkbenchLiveRoute({
    projectStatusPath: statusPath,
    url: SHARED_EDGE_ROUTE_URL,
    allowInsecureLocalTest: true,
    headers: {},
    headerNames: [],
    env: {
      EDGE_AGENT_AUTH_TOKEN_HELPER: helperPath
    },
    requestText: stubTransport
  });

  assert.equal(artifact.status, "pass");
  assert.deepEqual(artifact.request_header_names, ["X-HZ-Dev-Auth-Bypass-Token"]);
  assert.doesNotMatch(JSON.stringify(artifact), /secret-header-value/);
});

test("probe rejects served workbench HTML that references root-level Next assets", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ai-control-platform-live-probe-"));
  const statusPath = writeProjectStatus(dir);
  const requestText = (url, headers) => {
    const authorized = headers["X-HZ-Dev-Auth-Bypass-Token"] === "secret-header-value";
    if (!authorized) return stubTransport(url, headers);
    const pathname = new URL(url).pathname;
    if (pathname === "/projects/ai-control-platform/") {
      return Promise.resolve({
        url,
        finalUrl: url,
        status: 200,
        headers: { "content-type": "text/html; charset=utf-8" },
        body: [
          "<!doctype html><title>AI Control Platform Workbench</title>",
          "<link rel=\"preload\" href=\"/_next/static/chunks/main-app.js\">",
          "<script src=\"/_next/static/chunks/app/page.js\"></script>",
          "<link rel=\"icon\" href=\"/favicon.svg\">",
          "<body data-view=\"desktop\"><main data-bind=\"headline\">Workbench</main></body>"
        ].join(""),
        redirects: [],
        authRedirectDetected: false
      });
    }
    if (pathname === "/projects/ai-control-platform/api/workbench/projection") {
      return Promise.resolve({
        url,
        finalUrl: url,
        status: 200,
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ projection_id: "stub", status: "pass" }),
        redirects: [],
        authRedirectDetected: false
      });
    }
    return Promise.resolve({
      url,
      finalUrl: url,
      status: 404,
      headers: {},
      body: "not found",
      redirects: [],
      authRedirectDetected: false
    });
  };

  const artifact = await probeWorkbenchLiveRoute({
    projectStatusPath: statusPath,
    url: ROUTE_URL,
    allowInsecureLocalTest: true,
    headers: {
      "X-HZ-Dev-Auth-Bypass-Token": "secret-header-value"
    },
    headerNames: ["X-HZ-Dev-Auth-Bypass-Token"],
    requestText
  });

  assert.equal(artifact.status, "fail");
  assert.equal(artifact.workbench.referenced_assets_mounted, false);
  assert.ok(artifact.issues.some((issue) => issue.code === "referenced_assets_not_mounted"));
  assert.doesNotMatch(JSON.stringify(artifact), /secret-header-value/);
});

test("probe CLI output redacts cookie and header values before any network request", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ai-control-platform-live-probe-"));
  const statusPath = writeProjectStatus(dir, UNREACHABLE_ROUTE_URL);
  const outputPath = join(dir, "evidence.json");
  const result = await runCli([
    "--project-status",
    statusPath,
    "--url",
    UNREACHABLE_ROUTE_URL,
    "--output",
    outputPath,
    "--cookie-header",
    SECRET_COOKIE,
    "--header",
    `Authorization: ${SECRET_HEADER}`,
    "--allow-insecure-local-test"
  ]);
  const combinedOutput = `${result.stdout}\n${result.stderr}`;
  const artifact = JSON.parse(readFileSync(outputPath, "utf8"));

  assert.equal(result.status, 1);
  assert.equal(artifact.status, "fail");
  assert.match(combinedOutput, /"Cookie"/);
  assert.match(combinedOutput, /"Authorization"/);
  assert.doesNotMatch(combinedOutput, /secret-cookie-value/);
  assert.doesNotMatch(combinedOutput, /secret-header-value/);
});
