#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export AI_CONTROL_WORKBENCH_CLAUDE_PROXY="${AI_CONTROL_WORKBENCH_CLAUDE_PROXY:-/Users/hernando_zhao/codex/start-claude-deepseek-no-proxy.sh}"
export AI_CONTROL_WORKBENCH_CLAUDE_PROXY_SUPPORTS_MODEL_ARG="${AI_CONTROL_WORKBENCH_CLAUDE_PROXY_SUPPORTS_MODEL_ARG:-0}"
export AI_CONTROL_WORKBENCH_CLAUDE_PROXY_SUPPORTS_ROLE="${AI_CONTROL_WORKBENCH_CLAUDE_PROXY_SUPPORTS_ROLE:-0}"
export AI_CONTROL_WORKBENCH_CLAUDE_MODEL="${AI_CONTROL_WORKBENCH_CLAUDE_MODEL:-deepseek-v4-pro[1m]}"
export AI_CONTROL_WORKBENCH_CLAUDE_ROLE="${AI_CONTROL_WORKBENCH_CLAUDE_ROLE:-developer}"

exec "$SCRIPT_DIR/run-claude-child-worker.sh" "$@"
